/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ItinerariesIndexRouteImport } from './routes/itineraries.index'
import { Route as ItinerariesSlugRouteImport } from './routes/itineraries.$slug'
import { Route as SkIndexRouteImport } from './routes/sk.index'
import { Route as SkAboutRouteImport } from './routes/sk.about'
import { Route as SkDeliveryRouteImport } from './routes/sk.delivery'
import { Route as SkLettersRouteImport } from './routes/sk.letters'
import { Route as SkPricingRouteImport } from './routes/sk.pricing'
import { Route as SkPrivacyRouteImport } from './routes/sk.privacy'
import { Route as SkTermsRouteImport } from './routes/sk.terms'
import { Route as SkItinerariesIndexRouteImport } from './routes/sk.itineraries.index'
import { Route as SkItinerariesSlugRouteImport } from './routes/sk.itineraries.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesIndexRoute = ItinerariesIndexRouteImport.update({
  id: '/itineraries/',
  path: '/itineraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesSlugRoute = ItinerariesSlugRouteImport.update({
  id: '/itineraries/$slug',
  path: '/itineraries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SkIndexRoute = SkIndexRouteImport.update({
  id: '/sk/',
  path: '/sk/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkAboutRoute = SkAboutRouteImport.update({
  id: '/sk/about',
  path: '/sk/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SkDeliveryRoute = SkDeliveryRouteImport.update({
  id: '/sk/delivery',
  path: '/sk/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const SkLettersRoute = SkLettersRouteImport.update({
  id: '/sk/letters',
  path: '/sk/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const SkPricingRoute = SkPricingRouteImport.update({
  id: '/sk/pricing',
  path: '/sk/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SkPrivacyRoute = SkPrivacyRouteImport.update({
  id: '/sk/privacy',
  path: '/sk/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SkTermsRoute = SkTermsRouteImport.update({
  id: '/sk/terms',
  path: '/sk/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SkItinerariesIndexRoute = SkItinerariesIndexRouteImport.update({
  id: '/sk/itineraries/',
  path: '/sk/itineraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkItinerariesSlugRoute = SkItinerariesSlugRouteImport.update({
  id: '/sk/itineraries/$slug',
  path: '/sk/itineraries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/delivery': typeof DeliveryRoute
  '/letters': typeof LettersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/sk/about': typeof SkAboutRoute
  '/sk/delivery': typeof SkDeliveryRoute
  '/sk/letters': typeof SkLettersRoute
  '/sk/pricing': typeof SkPricingRoute
  '/sk/privacy': typeof SkPrivacyRoute
  '/sk/terms': typeof SkTermsRoute
  '/itineraries/': typeof ItinerariesIndexRoute
  '/sk/': typeof SkIndexRoute
  '/sk/itineraries/$slug': typeof SkItinerariesSlugRoute
  '/sk/itineraries/': typeof SkItinerariesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/delivery': typeof DeliveryRoute
  '/letters': typeof LettersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/sk/about': typeof SkAboutRoute
  '/sk/delivery': typeof SkDeliveryRoute
  '/sk/letters': typeof SkLettersRoute
  '/sk/pricing': typeof SkPricingRoute
  '/sk/privacy': typeof SkPrivacyRoute
  '/sk/terms': typeof SkTermsRoute
  '/itineraries': typeof ItinerariesIndexRoute
  '/sk': typeof SkIndexRoute
  '/sk/itineraries/$slug': typeof SkItinerariesSlugRoute
  '/sk/itineraries': typeof SkItinerariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/delivery': typeof DeliveryRoute
  '/letters': typeof LettersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/sk/about': typeof SkAboutRoute
  '/sk/delivery': typeof SkDeliveryRoute
  '/sk/letters': typeof SkLettersRoute
  '/sk/pricing': typeof SkPricingRoute
  '/sk/privacy': typeof SkPrivacyRoute
  '/sk/terms': typeof SkTermsRoute
  '/itineraries/': typeof ItinerariesIndexRoute
  '/sk/': typeof SkIndexRoute
  '/sk/itineraries/$slug': typeof SkItinerariesSlugRoute
  '/sk/itineraries/': typeof SkItinerariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/delivery'
    | '/letters'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/itineraries/$slug'
    | '/sk/about'
    | '/sk/delivery'
    | '/sk/letters'
    | '/sk/pricing'
    | '/sk/privacy'
    | '/sk/terms'
    | '/itineraries/'
    | '/sk/'
    | '/sk/itineraries/$slug'
    | '/sk/itineraries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/delivery'
    | '/letters'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/itineraries/$slug'
    | '/sk/about'
    | '/sk/delivery'
    | '/sk/letters'
    | '/sk/pricing'
    | '/sk/privacy'
    | '/sk/terms'
    | '/itineraries'
    | '/sk'
    | '/sk/itineraries/$slug'
    | '/sk/itineraries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/delivery'
    | '/letters'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/itineraries/$slug'
    | '/sk/about'
    | '/sk/delivery'
    | '/sk/letters'
    | '/sk/pricing'
    | '/sk/privacy'
    | '/sk/terms'
    | '/itineraries/'
    | '/sk/'
    | '/sk/itineraries/$slug'
    | '/sk/itineraries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DeliveryRoute: typeof DeliveryRoute
  LettersRoute: typeof LettersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ItinerariesSlugRoute: typeof ItinerariesSlugRoute
  SkAboutRoute: typeof SkAboutRoute
  SkDeliveryRoute: typeof SkDeliveryRoute
  SkLettersRoute: typeof SkLettersRoute
  SkPricingRoute: typeof SkPricingRoute
  SkPrivacyRoute: typeof SkPrivacyRoute
  SkTermsRoute: typeof SkTermsRoute
  ItinerariesIndexRoute: typeof ItinerariesIndexRoute
  SkIndexRoute: typeof SkIndexRoute
  SkItinerariesSlugRoute: typeof SkItinerariesSlugRoute
  SkItinerariesIndexRoute: typeof SkItinerariesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/': {
      id: '/itineraries/'
      path: '/itineraries'
      fullPath: '/itineraries/'
      preLoaderRoute: typeof ItinerariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/$slug': {
      id: '/itineraries/$slug'
      path: '/itineraries/$slug'
      fullPath: '/itineraries/$slug'
      preLoaderRoute: typeof ItinerariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk/': {
      id: '/sk/'
      path: '/sk'
      fullPath: '/sk/'
      preLoaderRoute: typeof SkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk/about': {
      id: '/sk/about'
      path: '/sk/about'
      fullPath: '/sk/about'
      preLoaderRoute: typeof SkAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk/delivery': {
      id: '/sk/delivery'
      path: '/sk/delivery'
      fullPath: '/sk/delivery'
      preLoaderRoute: typeof SkDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk/letters': {
      id: '/sk/letters'
      path: '/sk/letters'
      fullPath: '/sk/letters'
      preLoaderRoute: typeof SkLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk/pricing': {
      id: '/sk/pricing'
      path: '/sk/pricing'
      fullPath: '/sk/pricing'
      preLoaderRoute: typeof SkPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk/privacy': {
      id: '/sk/privacy'
      path: '/sk/privacy'
      fullPath: '/sk/privacy'
      preLoaderRoute: typeof SkPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk/terms': {
      id: '/sk/terms'
      path: '/sk/terms'
      fullPath: '/sk/terms'
      preLoaderRoute: typeof SkTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk/itineraries/': {
      id: '/sk/itineraries/'
      path: '/sk/itineraries'
      fullPath: '/sk/itineraries/'
      preLoaderRoute: typeof SkItinerariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk/itineraries/$slug': {
      id: '/sk/itineraries/$slug'
      path: '/sk/itineraries/$slug'
      fullPath: '/sk/itineraries/$slug'
      preLoaderRoute: typeof SkItinerariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DeliveryRoute: DeliveryRoute,
  LettersRoute: LettersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ItinerariesSlugRoute: ItinerariesSlugRoute,
  SkAboutRoute: SkAboutRoute,
  SkDeliveryRoute: SkDeliveryRoute,
  SkLettersRoute: SkLettersRoute,
  SkPricingRoute: SkPricingRoute,
  SkPrivacyRoute: SkPrivacyRoute,
  SkTermsRoute: SkTermsRoute,
  ItinerariesIndexRoute: ItinerariesIndexRoute,
  SkIndexRoute: SkIndexRoute,
  SkItinerariesSlugRoute: SkItinerariesSlugRoute,
  SkItinerariesIndexRoute: SkItinerariesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
